[package]
name = "kittynode-web"
version = "0.61.0"
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
kittynode-core = { version = "0.64.0", path = "../core" }
tracing-subscriber = "0.3.22"
eyre = { version = "0.6.12", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
tower = "0.5.2"
serde_json = "1.0.148"
tempfile = "3.24.0"
