[package]
name = "kittynode-web"
version = "0.50.0"
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
kittynode-core = { version = "0.53.0", path = "../core" }
tracing-subscriber = "0.3.20"
eyre = { version = "0.6.12", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
tower = "0.5.2"
