[package]
name = "kittynode-tauri"
version = "0.116.0"
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "kittynode_tauri_lib"

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
eyre = { version = "0.6.12", default-features = false, features = [
  "auto-install",
  "track-caller",
] }
async-trait = "0.1.89"
kittynode-core = { version = "0.60.0", path = "../../core" }
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tauri = { version = "2.9.5", features = ["devtools"] }
tauri-plugin-http = "2.5.4"
tauri-plugin-os = "2.3.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-shell = "2.3.3"
tokio = "1.48.0"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.9.0"

[dev-dependencies]
axum = { version = "0.8.8", features = ["json", "macros"] }
