[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "kittynode-core"
readme.workspace = true
repository.workspace = true
version = "0.4.0"

[dependencies]
bollard = "0.19.2"
eyre = { version = "0.6.12", default-features = false, features = [
  "auto-install",
  "track-caller",
] }
serde = { version = "1.0.223", features = ["derive"] }
toml = "0.9.5"
tracing = "0.1.41"
tokio-stream = "0.1.17"
home = "0.5.11"
hex = "0.4.3"
rand = "0.9.2"
sysinfo = "0.37.0"

[dev-dependencies]
tempfile = "3.22.0"
kittynode-web = { path = "../web" }
assert_cmd = "2.0.17"
serde_json = "1.0.145"
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
escargot = "0.5.8"
