[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "kittynode-core"
readme.workspace = true
repository.workspace = true
version = "0.4.0"

[dependencies]
bollard = "0.19.0"
eyre = { version = "0.6.12", default-features = false, features = [
  "auto-install",
  "track-caller",
] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
tracing = "0.1.41"
tokio-stream = "0.1.17"
home = "0.5.11"
hex = "0.4.3"
rand = "0.9.1"
sysinfo = "0.34.2"

[dev-dependencies]
tempfile = "3.20.0"
